name: Build and test
on:
  pull_request:
    branches: [main]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
        - name: build-and-test
          uses: "actions/checkout@v4"
        
        - name: Update dependencies
          run: npm install
        
        - name: Run prisma generate client
          run: npx prisma generate
          
        - name: Run npm tests
          run: npm test
  
    
