name: Deploy on main
on:
  pull_request:
    branches: [main]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
        - name: build-and-test
          uses: "actions/checkout@v4"
        
        - name: Update dependencies
          run: npm install
        
        - name: run tests
          run: npm test
  
    
